# Generated by Django 3.0.1 on 2020-01-02 21:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('title', models.CharField(help_text='Enter title', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CarPictureInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('ec6002f4-5a16-417e-8696-191074a94fc4'), help_text='Уникальный идентификатор', primary_key=True, serialize=False)),
                ('imprint', models.CharField(max_length=200)),
                ('due_back', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('a', 'Available'), ('r', 'Reserved')], default='m', help_text='Status', max_length=1)),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.CarPicture')),
            ],
            options={
                'ordering': ['due_back'],
            },
        ),
        migrations.DeleteModel(
            name='Portfolio',
        ),
        migrations.DeleteModel(
            name='PostImage',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Resume',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
