# Generated by Django 3.0.1 on 2020-01-09 11:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200103_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carpictureinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('90f13609-0222-436b-b545-ecea9bd0d437'), help_text='Уникальный идентификатор', primary_key=True, serialize=False),
        ),
    ]
