# Generated by Django 3.0.1 on 2020-01-09 11:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200109_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carpictureinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('83b664ff-ed2c-47ed-93c8-ca1ea6091cca'), help_text='Уникальный идентификатор', primary_key=True, serialize=False),
        ),
    ]
