# Generated by Django 3.0.1 on 2020-01-12 11:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200109_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carpictureinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('119beca0-c504-4727-ae69-6200e388f4e2'), help_text='Уникальный идентификатор', primary_key=True, serialize=False),
        ),
    ]
